In [60]:
import numpy as np

M = 2
N= 3
K = 1
L =1
a = np.array([[j*(M+1)+i,j*(M+1)+i+1,(j+1)*(M+1)+i,(j+1)*(M+1)+i+1] for i in range(M) for j in range(N) ])
b = np.array([[k*(M+1)*(N+1)+j*(M+1)+i,k*(M+1)*(N+1)+j*(M+1)+i+1,k*(M+1)*(N+1)+(j+1)*(M+1)+i,k*(M+1)*(N+1)+(j+1)*(M+1)+i+1,(k+1)*(M+1)*(N+1)+j*(M+1)+i,(k+1)*(M+1)*(N+1)+j*(M+1)+i+1,(k+1)*(M+1)*(N+1)+(j+1)*(M+1)+i,(k+1)*(M+1)*(N+1)+(j+1)*(M+1)+i+1] for i in range(M) for j in range(N) for k in range(K)])
#print(b)

d = np.array([[l*(M+1)*(K+1)*(N+1)+k*(M+1)*(N+1)+j*(M+1)+i,l*(M+1)*(K+1)*(N+1)+k*(M+1)*(N+1)+j*(M+1)+i+1,
                                     l*(M+1)*(K+1)*(N+1)+k*(M+1)*(N+1)+(j+1)*(M+1)+i,l*(M+1)*(K+1)*(N+1)+k*(M+1)*(N+1)+(j+1)*(M+1)+i+1,
                                     l*(M+1)*(K+1)*(N+1)+(k+1)*(M+1)*(N+1)+j*(M+1)+i,l*(M+1)*(K+1)*(N+1)+(k+1)*(M+1)*(N+1)+j*(M+1)+i+1,
                                     l*(M+1)*(K+1)*(N+1)+(k+1)*(M+1)*(N+1)+(j+1)*(M+1)+i,l*(M+1)*(K+1)*(N+1)+(k+1)*(M+1)*(N+1)+(j+1)*(M+1)+i+1,
                                     (l+1)*(M+1)*(K+1)*(N+1)+k*(M+1)*(N+1)+j*(M+1)+i,(l+1)*(M+1)*(K+1)*(N+1)+k*(M+1)*(N+1)+j*(M+1)+i+1,
                                     (l+1)*(M+1)*(K+1)*(N+1)+k*(M+1)*(N+1)+(j+1)*(M+1)+i,(l+1)*(M+1)*(K+1)*(N+1)+k*(M+1)*(N+1)+(j+1)*(M+1)+i+1,
                                     (l+1)*(M+1)*(K+1)*(N+1)+(k+1)*(M+1)*(N+1)+j*(M+1)+i,(l+1)*(M+1)*(K+1)*(N+1)+(k+1)*(M+1)*(N+1)+j*(M+1)+i+1,
                                     (l+1)*(M+1)*(K+1)*(N+1)+(k+1)*(M+1)*(N+1)+(j+1)*(M+1)+i,(l+1)*(M+1)*(K+1)*(N+1)+(k+1)*(M+1)*(N+1)+(j+1)*(M+1)+i+1] for i in range(M) for j in range(N) for k in range(K) for l in range(L)])



c = np.array([[k*(M+1)*(N+1)+j*(M+1)+i,k*(M+1)*(N+1)+j*(M+1)+i+1,k*(M+1)*(N+1)+(j+1)*(M+1)+i,k*(M+1)*(N+1)+(j+1)*(M+1)+i+1]for i in range(M) for j in range(N) for k in range(K+1)]
            +[[k*(M+1)*(N+1)+j*(M+1)+i,k*(M+1)*(N+1)+j*(M+1)+i+1,(k+1)*(M+1)*(N+1)+j*(M+1)+i,(k+1)*(M+1)*(N+1)+j*(M+1)+i+1]for i in range(M) for j in range(N+1) for k in range(K)]
            +[[k*(M+1)*(N+1)+j*(M+1)+i,k*(M+1)*(N+1)+(j+1)*(M+1)+i,(k+1)*(M+1)*(N+1)+j*(M+1)+i,(k+1)*(M+1)*(N+1)+(j+1)*(M+1)+i]for i in range(M+1) for j in range(N) for k in range(K)])
print(c,len(c))

d = np.array([[k*(M+1)*(N+1)+j*(M+1)+i,k*(M+1)*(N+1)+j*(M+1)+i+1]for  i in range(M) for j in range(N+1) for k in range(K+1)]
             +[[k*(M+1)*(N+1)+j*(M+1)+i,k*(M+1)*(N+1)+(j+1)*(M+1)+i]for i in range(M+1) for j in range(N) for k in range(K+1)]
            +[[k*(M+1)*(N+1)+j*(M+1)+i,(k+1)*(M+1)*(N+1)+j*(M+1)+i]for i in range(M+1) for j in range(N+1) for k in range(K)])
print(d,len(d))

f = [i +M*N*j for j in range(N+1) for i in range(M+1)]+ [M+i*(M+1) for i in range(N+1)]+[i*(M+1) for i in range(N+1)]+[(M+1)*(N+1)-i-1 for i in range(0,M+1)]

print(f,len(f))

[[ 0  1  3  4]
 [12 13 15 16]
 [ 3  4  6  7]
 [15 16 18 19]
 [ 6  7  9 10]
 [18 19 21 22]
 [ 1  2  4  5]
 [13 14 16 17]
 [ 4  5  7  8]
 [16 17 19 20]
 [ 7  8 10 11]
 [19 20 22 23]
 [ 0  1 12 13]
 [ 3  4 15 16]
 [ 6  7 18 19]
 [ 9 10 21 22]
 [ 1  2 13 14]
 [ 4  5 16 17]
 [ 7  8 19 20]
 [10 11 22 23]
 [ 0  3 12 15]
 [ 3  6 15 18]
 [ 6  9 18 21]
 [ 1  4 13 16]
 [ 4  7 16 19]
 [ 7 10 19 22]
 [ 2  5 14 17]
 [ 5  8 17 20]
 [ 8 11 20 23]] 29
[[ 0  1]
 [12 13]
 [ 3  4]
 [15 16]
 [ 6  7]
 [18 19]
 [ 9 10]
 [21 22]
 [ 1  2]
 [13 14]
 [ 4  5]
 [16 17]
 [ 7  8]
 [19 20]
 [10 11]
 [22 23]
 [ 0  3]
 [12 15]
 [ 3  6]
 [15 18]
 [ 6  9]
 [18 21]
 [ 1  4]
 [13 16]
 [ 4  7]
 [16 19]
 [ 7 10]
 [19 22]
 [ 2  5]
 [14 17]
 [ 5  8]
 [17 20]
 [ 8 11]
 [20 23]
 [ 0 12]
 [ 3 15]
 [ 6 18]
 [ 9 21]
 [ 1 13]
 [ 4 16]
 [ 7 19]
 [10 22]
 [ 2 14]
 [ 5 17]
 [ 8 20]
 [11 23]] 46
[0, 1, 2, 6, 7, 8, 12, 13, 14, 18, 19, 20, 2, 5, 8, 11, 0, 3, 6, 9, 11, 10, 9] 23
