In [57]:
from import_hack import *
from methodsnm.mesh_4d import *
from methodsnm.visualize import *
import numpy as np
m=8
mesh = StructuredTesseraktMesh(m,m,m,m)
#DrawMesh2D(mesh)
#print(mesh.points[mesh.elements()[6]])
for elnr, verts in enumerate(mesh.elements()):
    print(elnr,verts)
    trafo = mesh.trafo(elnr)
    print(trafo.map(np.array([0.5,0.5,0.5,0.5])))
    if elnr == 6:
        break
# print(len(mesh.vertices),len(mesh.bndry_vertices),len(mesh.edges),len(mesh.bndry_edges),len(mesh.faces),len(mesh.bndry_faces),len(mesh.volumes),len(mesh.bndry_volumes))

0 [  0   1   9  10  81  82  90  91 729 730 738 739 810 811 819 820]
[0.0625 0.0625 0.0625 0.0625]
1 [ 729  730  738  739  810  811  819  820 1458 1459 1467 1468 1539 1540
 1548 1549]
[0.0625 0.0625 0.1875 0.0625]
2 [1458 1459 1467 1468 1539 1540 1548 1549 2187 2188 2196 2197 2268 2269
 2277 2278]
[0.0625 0.0625 0.3125 0.0625]
3 [2187 2188 2196 2197 2268 2269 2277 2278 2916 2917 2925 2926 2997 2998
 3006 3007]
[0.0625 0.0625 0.4375 0.0625]
4 [2916 2917 2925 2926 2997 2998 3006 3007 3645 3646 3654 3655 3726 3727
 3735 3736]
[0.0625 0.0625 0.5625 0.0625]
5 [3645 3646 3654 3655 3726 3727 3735 3736 4374 4375 4383 4384 4455 4456
 4464 4465]
[0.0625 0.0625 0.6875 0.0625]
6 [4374 4375 4383 4384 4455 4456 4464 4465 5103 5104 5112 5113 5184 5185
 5193 5194]
[0.0625 0.0625 0.8125 0.0625]


In [58]:
from methodsnm.fes import *
fes = P1_Tesserakt_Space(mesh)
#print(fes.eltype)


In [59]:
from methodsnm.forms import *
from methodsnm.formint import *
from numpy import pi, cos ,sin

blf = BilinearForm(fes)
c = GlobalFunction(lambda x: 1, mesh = mesh)
blf += LaplaceIntegral(c)
blf += MassIntegral(c)
blf.assemble()

lf = LinearForm(fes)
f = GlobalFunction(lambda x: (1+pi**2)*cos(pi*x[1]), mesh = mesh)
lf += SourceIntegral(f)
lf.assemble()

In [60]:
print(blf.matrix, "\n", lf.vector)

  (0, 0)	0.0009775161732883681
  (0, 1)	0.0004892349231247608
  (0, 9)	0.0004892349231247608
  (0, 10)	9.53672961153535e-07
  (0, 81)	0.0004892349231247608
  (0, 82)	9.53672961153535e-07
  (0, 90)	9.53672961153535e-07
  (0, 91)	-0.00048732757720245366
  (0, 729)	0.0004892349231247608
  (0, 730)	9.53672961153535e-07
  (0, 738)	9.53672961153535e-07
  (0, 739)	-0.00048732757720245377
  (0, 810)	9.53672961153535e-07
  (0, 811)	-0.00048732757720245377
  (0, 819)	-0.00048732757720245377
  (0, 820)	-0.0009756088273660611
  (1, 0)	0.0004892349231247608
  (1, 1)	0.001955032347931989
  (1, 2)	0.0004892349231247608
  (1, 9)	9.53672961153535e-07
  (1, 10)	0.0009784698476047744
  (1, 11)	9.53672961153535e-07
  (1, 81)	9.53672961153535e-07
  (1, 82)	0.0009784698476047744
  (1, 83)	9.53672961153535e-07
  :	:
  (6559, 6477)	9.536756716589662e-07
  (6559, 6478)	0.0009784698530257852
  (6559, 6479)	9.536756716589662e-07
  (6559, 6549)	9.536756716589662e-07
  (6559, 6550)	0.0009784698530257852
  (6559, 6

In [61]:
uh = FEFunction(fes)
from scipy.sparse.linalg import spsolve
uh.vector = spsolve(blf.matrix, lf.vector)

In [62]:
from methodsnm.forms import compute_difference_L2

uex =  GlobalFunction(lambda x: cos(pi*x[1]), mesh = mesh)
l2diff = compute_difference_L2(uh, uex, mesh, intorder = 6)

print("l2diff =", l2diff)

l2diff = 0.016476910721807587
